"""initial_migration

Revision ID: 497081177b0a
Revises: 
Create Date: 2025-05-07 19:54:04.351679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.portfolio import TransactionType # For Enum in Transaction model

# revision identifiers, used by Alembic.
revision: str = '497081177b0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('price_change_percent', sa.Float(), nullable=True),
    sa.Column('day_high', sa.Float(), nullable=True),
    sa.Column('day_low', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('quote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_company_name'), 'stocks', ['company_name'], unique=False)
    op.create_index(op.f('ix_stocks_exchange'), 'stocks', ['exchange'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_industry'), 'stocks', ['industry'], unique=False)
    op.create_index(op.f('ix_stocks_sector'), 'stocks', ['sector'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)

    op.create_table('analysis_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.Enum('TECHNICAL', 'FUNDAMENTAL', 'SENTIMENT', 'COMPREHENSIVE', 'CHAETRA_SYNTHESIS', 'TRADING_SUGGESTION', name='analysistype'), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('summary_key_metric_1_name', sa.String(), nullable=True),
    sa.Column('summary_key_metric_1_value', sa.String(), nullable=True),
    sa.Column('summary_key_metric_2_name', sa.String(), nullable=True),
    sa.Column('summary_key_metric_2_value', sa.String(), nullable=True),
    sa.Column('overall_assessment', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('analysis_parameters', sa.JSON(), nullable=True),
    sa.Column('data_start_date', sa.DateTime(), nullable=True),
    sa.Column('data_end_date', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_outputs_analysis_type'), 'analysis_outputs', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_outputs_generated_at'), 'analysis_outputs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_analysis_outputs_id'), 'analysis_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_outputs_stock_id'), 'analysis_outputs', ['stock_id'], unique=False)

    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_buy_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_positions_id'), 'portfolio_positions', ['id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'SPLIT', 'FEE', 'DEPOSIT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_portfolio_positions_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_analysis_outputs_stock_id'), table_name='analysis_outputs')
    op.drop_index(op.f('ix_analysis_outputs_id'), table_name='analysis_outputs')
    op.drop_index(op.f('ix_analysis_outputs_generated_at'), table_name='analysis_outputs')
    op.drop_index(op.f('ix_analysis_outputs_analysis_type'), table_name='analysis_outputs')
    op.drop_table('analysis_outputs')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sector'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_industry'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_exchange'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_company_name'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
